<a href="https://colab.research.google.com/github/bhargavreddy111/Fraud-Detection/blob/master/Customer%20Churn%20Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
#from sklearn.feature_extraction.text import TfidfVectorizer

#NLTK-------------------------------
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.stem.snowball import SnowballStemmer
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
from nltk.corpus import stopwords
#from nltk.stemporter import PorterStemmer

# Import libraries for feature 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score as acc
from mlxtend.feature_selection import SequentialFeatureSelector as sfs

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn import metrics

import warnings
warnings.filterwarnings("ignore")


from google.colab import drive
drive.mount('/gdrive')
#Change current working directory to gdrive
%cd /gdrive


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


/usr/local/lib/python3.6/dist-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive
/gdrive


In [0]:
#Read files
textfile = r'/gdrive/My Drive/Assignment 5/Comments.csv'
textData = pd.read_csv(textfile) #creates a dataframe

CustInfofile = r'/gdrive/My Drive/Assignment 5/Customers.csv'
CustInfoData = pd.read_csv(CustInfofile)  #creates a dataframe

print(textData.shape)
print(CustInfoData.shape)


(2070, 2)
(2070, 17)


In [0]:
#Extract target column from Customer Info file
y_train = CustInfoData["TARGET"]
X_train = CustInfoData.drop(columns=["TARGET"]) #extracting training data without the target column
                     
print(X_train.shape)
print(textData.shape)
textData.head()
print(y_train)

(2070, 16)
(2070, 2)
0       Cancelled
1         Current
2         Current
3         Current
4       Cancelled
          ...    
2065    Cancelled
2066    Cancelled
2067    Cancelled
2068    Cancelled
2069    Cancelled
Name: TARGET, Length: 2070, dtype: object


In [0]:
#Tokenize - Split the sentences to lists of words
textData['CommentsTokenized'] = textData['Comments'].apply(word_tokenize)

export_csv = textData.to_csv(r'/gdrive/My Drive/Assignment 5/TextDataTokenized1.csv')

In [0]:
# Use Snowball stemmer.
stemmer1 = SnowballStemmer("english")

#Now do stemming - create a new dataframe to store stemmed version
newTextData1=pd.DataFrame()
newTextData1=textData.drop(columns=["CommentsTokenized","Comments"])
newTextData1['CommentsTokenizedStemmed'] = textData['CommentsTokenized'].apply(lambda x: [stemmer1.stem(y) for y in x]) # Stem every word.

export_csv = newTextData1.to_csv(r'/gdrive/My Drive/Assignment 5/newTextData_st1.csv')

#Join stemmed strings
newTextData1['CommentsTokenizedStemmed'] = newTextData1['CommentsTokenizedStemmed'].apply(lambda x: " ".join(x))

export_csv = newTextData1.to_csv(r'/gdrive/My Drive/Assignment 5/newTextData-Joined_st1.csv')

In [0]:
textData.head()

In [0]:
cv1 = CountVectorizer(lowercase=False)
counts1 = cv1.fit_transform(newTextData1.CommentsTokenizedStemmed)
print(counts1.shape)

(2070, 466)


In [0]:
# Use Porter stemmer.
stemmer2 = PorterStemmer()

#Now do stemming - create a new dataframe to store stemmed version
newTextData2=pd.DataFrame()
newTextData2=textData.drop(columns=["CommentsTokenized","Comments"])
newTextData2['CommentsTokenizedStemmed'] = textData['CommentsTokenized'].apply(lambda x: [stemmer2.stem(y) for y in x]) # Stem every word.

export_csv = newTextData2.to_csv(r'/gdrive/My Drive/Assignment 5/newTextData_st2.csv')

#Join stemmed strings
newTextData2['CommentsTokenizedStemmed'] = newTextData2['CommentsTokenizedStemmed'].apply(lambda x: " ".join(x))

export_csv = newTextData2.to_csv(r'/gdrive/My Drive/Assignment 5/newTextData-Joined_st2.csv')

In [0]:
cv2 = CountVectorizer(lowercase=False)
counts2 = cv2.fit_transform(newTextData2.CommentsTokenizedStemmed)
print(counts2.shape)

(2070, 474)


In [0]:
# Use Lancaster stemmer.
stemmer3 = LancasterStemmer()

#Now do stemming - create a new dataframe to store stemmed version
newTextData3=pd.DataFrame()
newTextData3=textData.drop(columns=["CommentsTokenized","Comments"])
newTextData3['CommentsTokenizedStemmed'] = textData['CommentsTokenized'].apply(lambda x: [stemmer3.stem(y) for y in x]) # Stem every word.

export_csv = newTextData3.to_csv(r'/gdrive/My Drive/Assignment 5/newTextData_st3.csv')

#Join stemmed strings
newTextData3['CommentsTokenizedStemmed'] = newTextData3['CommentsTokenizedStemmed'].apply(lambda x: " ".join(x))

export_csv = newTextData3.to_csv(r'/gdrive/My Drive/Assignment 5/newTextData-Joined_st3.csv')

In [0]:
cv3 = CountVectorizer(lowercase=False)
counts3 = cv3.fit_transform(newTextData3.CommentsTokenizedStemmed)
print(counts3.shape)

(2070, 450)


In [0]:
#Do Bag-Of-Words model - Term - Document Matrix
#Learn the vocabulary dictionary and return term-document matrix.
#count_vect = CountVectorizer(stop_words=None)
count_vect1 = CountVectorizer(stop_words='english',lowercase=False)
TD_counts1 = count_vect1.fit_transform(newTextData1.CommentsTokenizedStemmed)
print(TD_counts1.shape)
TD_counts1.dtype
print(count_vect1.get_feature_names())
#print(TD_counts)
DF_TD_Counts1=pd.DataFrame(TD_counts1.toarray())
#print(DF_TD_Counts)
export_csv = DF_TD_Counts1.to_csv(r'/gdrive/My Drive/Assignment 5/TD_counts1-TokenizedStemmed.csv')


(2070, 354)
['3399', '3g', 'abysm', 'access', 'accessori', 'adapt', 'add', 'addit', 'additon', 'address', 'adit', 'adress', 'advertis', 'afraid', 'alway', 'angel', 'angri', 'ani', 'anoth', 'anyth', 'anytim', 'area', 'asap', 'ask', 'bad', 'basic', 'bateri', 'batteri', 'becaus', 'believ', 'better', 'bigger', 'book', 'bought', 'brain', 'bring', 'built', 'busi', 'button', 'buy', 'cancel', 'cancer', 'car', 'care', 'carrier', 'caus', 'cc', 'cell', 'certain', 'chang', 'charg', 'charger', 'check', 'chip', 'citi', 'claim', 'cleariti', 'cold', 'comapr', 'compani', 'compar', 'competit', 'complain', 'complaint', 'concept', 'connect', 'consisit', 'consist', 'constan', 'contact', 'continu', 'contract', 'correct', 'cost', 'coupl', 'cover', 'coverag', 'creat', 'credit', 'cstmer', 'cstmr', 'current', 'cust', 'custom', 'customr', 'date', 'day', 'dead', 'decent', 'defect', 'deo', 'did', 'die', 'differ', 'difficult', 'digiti', 'direct', 'disabl', 'doe', 'don', 'dont', 'drop', 'dure', 'easier', 'effect', '

In [0]:
#Do Bag-Of-Words model - Term - Document Matrix for Porter Stemmer data
#Learn the vocabulary dictionary and return term-document matrix.
#count_vect = CountVectorizer(stop_words=None)
count_vect2 = CountVectorizer(stop_words='english',lowercase=True)
TD_counts2 = count_vect2.fit_transform(newTextData2.CommentsTokenizedStemmed)
print(TD_counts2.shape)
TD_counts2.dtype
print(count_vect2.get_feature_names())
#print(TD_counts)
DF_TD_Counts2=pd.DataFrame(TD_counts2.toarray())
#print(DF_TD_Counts)
export_csv = DF_TD_Counts2.to_csv(r'/gdrive/My Drive/Assignment 5/TD_counts2-TokenizedStemmed.csv')

(2070, 358)
['3399', '3g', 'abysm', 'access', 'accessori', 'adapt', 'add', 'addit', 'additon', 'address', 'adit', 'adress', 'advertis', 'afraid', 'alway', 'angel', 'angri', 'ani', 'anoth', 'anyth', 'anytim', 'area', 'asap', 'ask', 'bad', 'basic', 'bateri', 'batteri', 'becaus', 'believ', 'better', 'bigger', 'book', 'bought', 'brain', 'bring', 'built', 'busi', 'button', 'buy', 'cancel', 'cancer', 'car', 'care', 'carrier', 'caus', 'cc', 'cell', 'certain', 'chang', 'charg', 'charger', 'check', 'chip', 'citi', 'claim', 'cleariti', 'cold', 'comapr', 'compani', 'compar', 'competit', 'complain', 'complaint', 'concept', 'connect', 'consisit', 'consist', 'constanli', 'contact', 'continu', 'contract', 'correct', 'cost', 'coupl', 'cover', 'coverag', 'creat', 'credit', 'cstmer', 'cstmr', 'current', 'cust', 'custom', 'customr', 'date', 'day', 'dead', 'decent', 'defect', 'deo', 'did', 'die', 'differ', 'difficult', 'digiti', 'direct', 'disabl', 'doe', 'don', 'dont', 'drop', 'dure', 'easier', 'effect',

In [0]:
#Do Bag-Of-Words model - Term - Document Matrix for Lancaster Stemmer data
#Learn the vocabulary dictionary and return term-document matrix.
#count_vect = CountVectorizer(stop_words=None)
count_vect3 = CountVectorizer(stop_words='english',lowercase=False)
TD_counts3 = count_vect3.fit_transform(newTextData3.CommentsTokenizedStemmed)
print(TD_counts3.shape)
TD_counts3.dtype
print(count_vect3.get_feature_names())
#print(TD_counts)
DF_TD_Counts3=pd.DataFrame(TD_counts3.toarray())
#print(DF_TD_Counts)
export_csv = DF_TD_Counts3.to_csv(r'/gdrive/My Drive/Assignment 5/TD_counts3-TokenizedStemmed.csv')

(2070, 364)
['3399', '3g', 'abysm', 'access', 'ad', 'adapt', 'addit', 'additon', 'address', 'adit', 'adress', 'advert', 'afraid', 'aft', 'al', 'alway', 'angel', 'angry', 'anoth', 'anyth', 'anytim', 'ar', 'asap', 'ask', 'bad', 'bas', 'batery', 'battery', 'becaus', 'believ', 'bet', 'big', 'bil', 'book', 'bought', 'brain', 'bring', 'built', 'busy', 'button', 'buy', 'cal', 'cancel', 'car', 'carry', 'caus', 'cc', 'cel', 'certain', 'chang', 'charg', 'check', 'chip', 'city', 'claim', 'clear', 'cold', 'comapr', 'comp', 'company', 'competit', 'complain', 'complaint', 'conceiv', 'connect', 'consisit', 'consist', 'const', 'contact', 'continu', 'contract', 'correct', 'cost', 'coupl', 'cov', 'cre', 'credit', 'cstmer', 'cstmr', 'cur', 'cust', 'custom', 'customr', 'dat', 'day', 'dead', 'dec', 'defect', 'deo', 'did', 'die', 'diff', 'difficult', 'digit', 'direct', 'dis', 'doe', 'don', 'dont', 'drop', 'dur', 'dying', 'easy', 'effect', 'encount', 'end', 'enemy', 'equip', 'ev', 'everytim', 'everywh', 'evr

In [0]:
#Compute TF-IDF Matrix
tfidf_transformer = TfidfTransformer()
X_train_tfidf1 = tfidf_transformer.fit_transform(TD_counts1)
print(X_train_tfidf1.shape)
DF_TF_IDF1=pd.DataFrame(X_train_tfidf1.toarray())
print(DF_TF_IDF1)
export_csv= DF_TF_IDF1.to_csv(r'/gdrive/My Drive/Assignment 5/TFIDF_counts-TokenizedStemmed_1.csv')


(2070, 354)
      0    1    2    3        4    5    ...  348  349  350  351  352  353
0     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.27568  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...      ...  ...  ...  ...  ...  ...  ...  ...  ...
2065  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2066  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2067  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2068  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2069  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

[2070 rows x 354 columns]


In [0]:
DF_TF_IDF1.head()

0    1    2    3        4    5    ...  348  349  350  351  352  353
0  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.27568  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 354 columns]

In [0]:
#Compute TF-IDF Matrix
tfidf_transformer = TfidfTransformer()
X_train_tfidf2 = tfidf_transformer.fit_transform(TD_counts2)
print(X_train_tfidf2.shape)
DF_TF_IDF2=pd.DataFrame(X_train_tfidf2.toarray())
print(DF_TF_IDF2)
export_csv= DF_TF_IDF2.to_csv(r'/gdrive/My Drive/Assignment 5/TFIDF_counts-TokenizedStemmed_2.csv')

(2070, 358)
      0    1    2    3        4    5    ...  352  353  354  355  356  357
0     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.27568  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...      ...  ...  ...  ...  ...  ...  ...  ...  ...
2065  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2066  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2067  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2068  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0
2069  0.0  0.0  0.0  0.0  0.00000  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0

[2070 rows x 358 columns]


In [0]:
#Compute TF-IDF Matrix
tfidf_transformer = TfidfTransformer()
X_train_tfidf3 = tfidf_transformer.fit_transform(TD_counts3)
print(X_train_tfidf3.shape)
DF_TF_IDF3=pd.DataFrame(X_train_tfidf3.toarray())
print(DF_TF_IDF3)
export_csv= DF_TF_IDF3.to_csv(r'/gdrive/My Drive/Assignment 5/TFIDF_counts-TokenizedStemmed_3.csv')

(2070, 364)
      0    1    2         3    4    5    6    ...  357  358  359  360  361  362  363
0     0.0  0.0  0.0  0.000000  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.275669  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.000000  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.000000  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.000000  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
2065  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2066  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2067  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2068  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2069  0.0  0.0  0.0  0.000000  0.0  0.0  0.0  ...  0.

In [0]:
#Add ID column
print(CustInfoData.shape)
X_train = CustInfoData.drop(columns=["TARGET"]) #extracting training data without the target column
print(X_train.shape)
DF_TF_IDF1 = pd.concat([newTextData1['ID'], DF_TF_IDF1], axis = 1)
DF_TF_IDF1.head()

(2070, 17)
(2070, 16)


ID    0    1    2    3        4  ...  348  349  350  351  352  353
0  1309  0.0  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0
1  3556  0.0  0.0  0.0  0.0  0.27568  ...  0.0  0.0  0.0  0.0  0.0  0.0
2  2230  0.0  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0
3  2312  0.0  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0
4  3327  0.0  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 355 columns]

In [0]:
#Merge Files
#combined=pd.concat([X_train, DF_TF_IDF_SelectedFeatures], axis=1)
combined = X_train.join(DF_TF_IDF1.set_index('ID'), on = 'ID')
print(combined.shape)
print(combined)
export_csv= combined.to_csv(r'/gdrive/My Drive/Assignment 5/Combined-Cust+TFIDF.csv')

(2070, 370)
        ID Sex Status  Children  Est_Income  ...  349  350  351  352  353
0        1   F      S         1    38000.00  ...  0.0  0.0  0.0  0.0  0.0
1        6   M      M         2    29616.00  ...  0.0  0.0  0.0  0.0  0.0
2        8   M      M         0    19732.80  ...  0.0  0.0  0.0  0.0  0.0
3       11   M      S         2       96.33  ...  0.0  0.0  0.0  0.0  0.0
4       14   F      M         2    52004.80  ...  0.0  0.0  0.0  0.0  0.0
...    ...  ..    ...       ...         ...  ...  ...  ...  ...  ...  ...
2065  3821   F      S         0    78851.30  ...  0.0  0.0  0.0  0.0  0.0
2066  3822   F      S         1    17540.70  ...  0.0  0.0  0.0  0.0  0.0
2067  3823   F      M         0    83891.90  ...  0.0  0.0  0.0  0.0  0.0
2068  3824   F      M         2    28220.80  ...  0.0  0.0  0.0  0.0  0.0
2069  3825   F      S         0    28589.10  ...  0.0  0.0  0.0  0.0  0.0

[2070 rows x 370 columns]


In [0]:
#Do one Hot encoding for categorical features
X_cat = ["Sex","Status","Car_Owner","Paymethod","LocalBilltype","LongDistanceBilltype"]
#X_cat = combined.select_dtypes(exclude=['int','float64'])
print(X_cat)
combined_one_hot = pd.get_dummies(combined,columns=X_cat)
print(combined_one_hot.shape)
export_csv= combined_one_hot.to_csv(r'/gdrive/My Drive/Assignment 5/combined_one_hot.csv')

['Sex', 'Status', 'Car_Owner', 'Paymethod', 'LocalBilltype', 'LongDistanceBilltype']
(2070, 378)


In [0]:
#splitting the traindata before proceeding for feature selection
X_trainf, X_test, y_trainf, y_test = train_test_split(combined_one_hot, y_train, test_size = 0.2, random_state = 42)
X_trainf.shape

(1656, 378)

In [0]:
#Feature selection
new_DF_TF_IDF1 = SelectKBest(score_func=chi2, k=50).fit(X_trainf,y_trainf)

new_X_trainf =  pd.DataFrame(new_DF_TF_IDF1.transform(X_trainf))
print(new_X_trainf.head())
#filering X_test also for prediction
new_X_test = pd.DataFrame(new_DF_TF_IDF1.transform(X_test))


DF_TF_IDF_Selected1= pd.DataFrame(new_X_trainf)
print(DF_TF_IDF_Selected1)

export_csv= DF_TF_IDF_Selected1.to_csv(r'/gdrive/My Drive/Assignment 5/TFIDF_counts-Selected Features1.csv')


       0    1         2       3      4    5   ...   44   45   46   47   48   49
0  1517.0  0.0  95448.60   29.46  24.24  0.0  ...  0.0  1.0  1.0  0.0  0.0  0.0
1  1892.0  0.0  17138.20  104.69  20.01  0.0  ...  1.0  0.0  0.0  1.0  0.0  1.0
2   339.0  0.0  92564.10   74.86  23.17  0.0  ...  1.0  0.0  0.0  1.0  1.0  0.0
3  2236.0  0.0  43000.00   65.79  42.00  0.0  ...  1.0  0.0  0.0  1.0  0.0  0.0
4   996.0  0.0   2031.61  109.04  21.64  0.0  ...  1.0  0.0  1.0  0.0  0.0  0.0

[5 rows x 50 columns]
          0    1         2       3      4    5   ...   44   45   46   47   48   49
0     1517.0  0.0  95448.60   29.46  24.24  0.0  ...  0.0  1.0  1.0  0.0  0.0  0.0
1     1892.0  0.0  17138.20  104.69  20.01  0.0  ...  1.0  0.0  0.0  1.0  0.0  1.0
2      339.0  0.0  92564.10   74.86  23.17  0.0  ...  1.0  0.0  0.0  1.0  1.0  0.0
3     2236.0  0.0  43000.00   65.79  42.00  0.0  ...  1.0  0.0  0.0  1.0  0.0  0.0
4      996.0  0.0   2031.61  109.04  21.64  0.0  ...  1.0  0.0  1.0  0.0  0.0  0.0

In [0]:
#Feature selection
new_DF_TF_IDF2 = SelectKBest(score_func=chi2, k=30).fit(X_trainf,y_trainf)

new_X_trainf2 =  pd.DataFrame(new_DF_TF_IDF2.transform(X_trainf))
print(new_X_trainf2.head())
#filering X_test also for prediction
new_X_test2 = pd.DataFrame(new_DF_TF_IDF2.transform(X_test))


DF_TF_IDF_Selected2= pd.DataFrame(new_X_trainf2)
print(DF_TF_IDF_Selected2)

export_csv= DF_TF_IDF_Selected2.to_csv(r'/gdrive/My Drive/Assignment 5/TFIDF_counts-Selected Features2.csv')

       0    1         2       3      4    5   ...   24        25   26   27   28   29
0  1517.0  0.0  95448.60   29.46  24.24  0.0  ...  0.0  0.348322  1.0  1.0  0.0  0.0
1  1892.0  0.0  17138.20  104.69  20.01  0.0  ...  0.0  0.000000  0.0  0.0  1.0  0.0
2   339.0  0.0  92564.10   74.86  23.17  0.0  ...  0.0  0.000000  0.0  0.0  1.0  1.0
3  2236.0  0.0  43000.00   65.79  42.00  0.0  ...  0.0  0.000000  0.0  0.0  1.0  0.0
4   996.0  0.0   2031.61  109.04  21.64  0.0  ...  0.0  0.000000  0.0  1.0  0.0  0.0

[5 rows x 30 columns]
          0    1         2       3      4   ...        25   26   27   28   29
0     1517.0  0.0  95448.60   29.46  24.24  ...  0.348322  1.0  1.0  0.0  0.0
1     1892.0  0.0  17138.20  104.69  20.01  ...  0.000000  0.0  0.0  1.0  0.0
2      339.0  0.0  92564.10   74.86  23.17  ...  0.000000  0.0  0.0  1.0  1.0
3     2236.0  0.0  43000.00   65.79  42.00  ...  0.000000  0.0  0.0  1.0  0.0
4      996.0  0.0   2031.61  109.04  21.64  ...  0.000000  0.0  1.0  0.0  0.0

In [0]:
#Feature selection
new_DF_TF_IDF3 = SelectKBest(score_func=chi2, k=90).fit(X_trainf,y_trainf)

new_X_trainf3 =  pd.DataFrame(new_DF_TF_IDF3.transform(X_trainf))
print(new_X_trainf3.head())
#filering X_test also for prediction
new_X_test3 = pd.DataFrame(new_DF_TF_IDF3.transform(X_test))


DF_TF_IDF_Selected3= pd.DataFrame(new_X_trainf3)
print(DF_TF_IDF_Selected3)

export_csv= DF_TF_IDF_Selected3.to_csv(r'/gdrive/My Drive/Assignment 5/TFIDF_counts-Selected Features3.csv')

       0    1         2       3          4   ...   85   86   87   88   89
0  1517.0  0.0  95448.60   29.46  53.680000  ...  1.0  0.0  0.0  0.0  0.0
1  1892.0  0.0  17138.20  104.69  63.786667  ...  0.0  1.0  0.0  1.0  1.0
2   339.0  0.0  92564.10   74.86  49.133333  ...  0.0  1.0  1.0  0.0  0.0
3  2236.0  0.0  43000.00   65.79  21.000000  ...  0.0  1.0  0.0  1.0  0.0
4   996.0  0.0   2031.61  109.04  20.300000  ...  1.0  0.0  0.0  1.0  0.0

[5 rows x 90 columns]
          0    1         2       3          4   ...   85   86   87   88   89
0     1517.0  0.0  95448.60   29.46  53.680000  ...  1.0  0.0  0.0  0.0  0.0
1     1892.0  0.0  17138.20  104.69  63.786667  ...  0.0  1.0  0.0  1.0  1.0
2      339.0  0.0  92564.10   74.86  49.133333  ...  0.0  1.0  1.0  0.0  0.0
3     2236.0  0.0  43000.00   65.79  21.000000  ...  0.0  1.0  0.0  1.0  0.0
4      996.0  0.0   2031.61  109.04  20.300000  ...  1.0  0.0  0.0  1.0  0.0
...      ...  ...       ...     ...        ...  ...  ...  ...  ...  ...

In [0]:
#Construct a Decision Tree Classifier on combined data

clf1=DecisionTreeClassifier()
RF_Comb = clf1.fit(new_X_trainf,y_trainf)
print("Accuracy score (training): {0:.6f}".format(clf1.score(new_X_trainf, y_trainf)))
rf_predictions = clf1.predict(new_X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Accuracy score (training): 1.000000
Confusion Matrix:
[[122  35]
 [ 46 211]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.73      0.78      0.75       157
     Current       0.86      0.82      0.84       257

    accuracy                           0.80       414
   macro avg       0.79      0.80      0.79       414
weighted avg       0.81      0.80      0.81       414



In [0]:
#Construct a Decision Tree Classifier on combined data

clf1=DecisionTreeClassifier()
RF_Comb = clf1.fit(new_X_trainf2,y_trainf)
print("Accuracy score (training): {0:.6f}".format(clf1.score(new_X_trainf2, y_trainf)))
rf_predictions = clf1.predict(new_X_test2)
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Accuracy score (training): 1.000000
Confusion Matrix:
[[124  33]
 [ 39 218]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.76      0.79      0.78       157
     Current       0.87      0.85      0.86       257

    accuracy                           0.83       414
   macro avg       0.81      0.82      0.82       414
weighted avg       0.83      0.83      0.83       414



In [0]:
#Construct a Decision Tree Classifier on combined data

clf1=DecisionTreeClassifier()
RF_Comb = clf1.fit(new_X_trainf3,y_trainf)
print("Accuracy score (training): {0:.6f}".format(clf1.score(new_X_trainf3, y_trainf)))
rf_predictions = clf1.predict(new_X_test3)
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Accuracy score (training): 1.000000
Confusion Matrix:
[[129  28]
 [ 51 206]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.72      0.82      0.77       157
     Current       0.88      0.80      0.84       257

    accuracy                           0.81       414
   macro avg       0.80      0.81      0.80       414
weighted avg       0.82      0.81      0.81       414



In [0]:
#Construct a MLP Classifier on combined data

clf2=MLPClassifier()
RF_Comb = clf2.fit(new_X_trainf,y_trainf)
print("Accuracy score (training): {0:.6f}".format(clf2.score(new_X_trainf, y_trainf)))
rf_predictions = clf2.predict(new_X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Accuracy score (training): 0.440217
Confusion Matrix:
[[157   0]
 [235  22]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.40      1.00      0.57       157
     Current       1.00      0.09      0.16       257

    accuracy                           0.43       414
   macro avg       0.70      0.54      0.36       414
weighted avg       0.77      0.43      0.31       414



In [0]:
#Construct a MLP Classifier on combined data

clf2=MLPClassifier()
RF_Comb = clf2.fit(new_X_trainf2,y_trainf)
print("Accuracy score (training): {0:.6f}".format(clf2.score(new_X_trainf2, y_trainf)))
rf_predictions = clf2.predict(new_X_test2)
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Accuracy score (training): 0.407005
Confusion Matrix:
[[157   0]
 [251   6]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.38      1.00      0.56       157
     Current       1.00      0.02      0.05       257

    accuracy                           0.39       414
   macro avg       0.69      0.51      0.30       414
weighted avg       0.77      0.39      0.24       414



In [0]:
#Construct a MLP Classifier on combined data

clf2=MLPClassifier()
RF_Comb = clf2.fit(new_X_trainf3,y_trainf)
print("Accuracy score (training): {0:.6f}".format(clf2.score(new_X_trainf3, y_trainf)))
rf_predictions = clf2.predict(new_X_test3)
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Accuracy score (training): 0.408816
Confusion Matrix:
[[157   0]
 [249   8]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.39      1.00      0.56       157
     Current       1.00      0.03      0.06       257

    accuracy                           0.40       414
   macro avg       0.69      0.52      0.31       414
weighted avg       0.77      0.40      0.25       414



In [0]:
#Construct a Random Forest Classifier on combined data

clf3=RandomForestClassifier()
RF_Comb = clf3.fit(new_X_trainf,y_trainf)
print("Accuracy score (training): {0:.6f}".format(clf3.score(new_X_trainf, y_trainf)))
rf_predictions = clf3.predict(new_X_test)
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Accuracy score (training): 0.985507
Confusion Matrix:
[[126  31]
 [ 33 224]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.79      0.80      0.80       157
     Current       0.88      0.87      0.88       257

    accuracy                           0.85       414
   macro avg       0.84      0.84      0.84       414
weighted avg       0.85      0.85      0.85       414



In [0]:
#Construct a Random Forest Classifier on combined data

clf3=RandomForestClassifier()
RF_Comb = clf3.fit(new_X_trainf2,y_trainf)
print("Accuracy score (training): {0:.6f}".format(clf3.score(new_X_trainf2, y_trainf)))
rf_predictions = clf3.predict(new_X_test2)
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Accuracy score (training): 0.983092
Confusion Matrix:
[[127  30]
 [ 29 228]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.81      0.81      0.81       157
     Current       0.88      0.89      0.89       257

    accuracy                           0.86       414
   macro avg       0.85      0.85      0.85       414
weighted avg       0.86      0.86      0.86       414



In [0]:
#Construct a Random Forest Classifier on combined data

clf3=RandomForestClassifier()
RF_Comb = clf3.fit(new_X_trainf3,y_trainf)
print("Accuracy score (training): {0:.6f}".format(clf3.score(new_X_trainf3, y_trainf)))
rf_predictions = clf3.predict(new_X_test3)
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_predictions))
print("Classification Report")
print(classification_report(y_test, rf_predictions))

Accuracy score (training): 0.986715
Confusion Matrix:
[[127  30]
 [ 34 223]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.79      0.81      0.80       157
     Current       0.88      0.87      0.87       257

    accuracy                           0.85       414
   macro avg       0.84      0.84      0.84       414
weighted avg       0.85      0.85      0.85       414



In [0]:
# Build DT classifier to use in feature selection
clfw1 = DecisionTreeClassifier()

# Build step forward feature selection
sfs1 = sfs(clfw1,
           k_features=30,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=5)

# Perform SFFS
sfs1 = sfs1.fit(X_trainf, y_trainf)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 378 out of 378 | elapsed:    5.6s finished

[2019-12-08 23:02:04] Features: 1/30 -- score: 0.863503527981743[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 377 out of 377 | elapsed:    7.1s finished

[2019-12-08 23:02:11] Features: 2/30 -- score: 0.8737608936156601[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 376 out of 376 | elapsed:    7.3s finished

[2019-12-08 23:02:18] Features: 3/30 -- score: 0.8785984035013993[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [0]:
#copying selected features
selected_features1 = list(sfs1.k_feature_names_)
print(selected_features1)

['Usage', 0, 2, 5, 8, 13, 15, 16, 17, 24, 25, 37, 41, 48, 50, 60, 62, 66, 67, 106, 122, 132, 135, 158, 161, 192, 220, 315, 'Sex_F', 'LongDistanceBilltype_Standard']


In [0]:
#using the selected features for full model - default decision tree classifier
clfw1 = DecisionTreeClassifier()
clfw1.fit(X_trainf[selected_features1], y_trainf)
y_pred = clfw1.predict(X_test[selected_features1])
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

   Cancelled       0.77      0.85      0.81       157
     Current       0.90      0.85      0.88       257

    accuracy                           0.85       414
   macro avg       0.84      0.85      0.84       414
weighted avg       0.86      0.85      0.85       414



In [0]:
# Build RF classifier to use in feature selection
clfw2 = RandomForestClassifier(n_estimators = 30, random_state = 42)

# Build step forward feature selection
sfs2 = sfs(clfw2,
           k_features=30,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=5)

# Perform SFFS
sfs2 = sfs2.fit(X_trainf, y_trainf)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 378 out of 378 | elapsed:  1.2min finished

[2019-12-09 00:40:58] Features: 1/30 -- score: 0.8604914908190852[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 377 out of 377 | elapsed:  1.8min finished

[2019-12-09 00:42:45] Features: 2/30 -- score: 0.8749821367314906[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 376 out of 376 | elapsed:  1.7min finished

[2019-12-09 00:44:27] Features: 3/30 -- score: 0.884040142994389[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [0]:
#copying selected features
selected_features2 = list(sfs2.k_feature_names_)
print(selected_features2)

['Age', 3, 4, 11, 33, 53, 58, 68, 70, 89, 92, 123, 128, 141, 144, 161, 163, 175, 201, 207, 220, 283, 286, 331, 333, 337, 347, 351, 'Sex_F', 'Sex_M']


In [0]:
#using the selected features for full model - default Random Forest classifier
clfw2 = RandomForestClassifier()
clfw2.fit(X_trainf[selected_features2], y_trainf)
y_pred = clfw2.predict(X_test[selected_features2])
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

   Cancelled       0.83      0.87      0.85       157
     Current       0.92      0.89      0.90       257

    accuracy                           0.88       414
   macro avg       0.87      0.88      0.88       414
weighted avg       0.88      0.88      0.88       414



In [0]:
# Build Gradient Boosting Classifier to use in feature selection
clfw3 = GradientBoostingClassifier()

# Build step forward feature selection
sfs3 = sfs(clfw3,
           k_features=30,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=5)

# Perform SFFS
sfs3 = sfs3.fit(X_trainf, y_trainf)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 378 out of 378 | elapsed:  1.4min finished

[2019-12-09 01:50:51] Features: 1/30 -- score: 0.786844516213715[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 377 out of 377 | elapsed:  2.1min finished

[2019-12-09 01:52:58] Features: 2/30 -- score: 0.8116088964481932[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.4s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 376 out of 376 | elapsed:  2.3min finished

[2019-12-09 01:55:17] Features: 3/30 -- score: 0.8484342202647447[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   

In [0]:
#copying selected features
selected_features3 = list(sfs3.k_feature_names_)
print(selected_features3)

['Est_Income', 'Age', 'LongDistance', 'Local', 0, 3, 5, 10, 11, 13, 15, 16, 26, 31, 34, 35, 41, 44, 45, 46, 56, 57, 60, 61, 72, 94, 193, 299, 303, 'Sex_F']


In [0]:
#using the selected features for full model - default Gradient Boosting classifier
clfw3.fit(X_trainf[selected_features3], y_trainf)
y_pred = clfw3.predict(X_test[selected_features3])
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

   Cancelled       0.82      0.70      0.76       157
     Current       0.83      0.91      0.87       257

    accuracy                           0.83       414
   macro avg       0.83      0.80      0.81       414
weighted avg       0.83      0.83      0.83       414

